###############################################################################
# Database - RDS for SQL Server
#
# Key constraint: the brief specifies db.t3.medium. Burstable instance classes
# are supported only on SQL Server Express and Web editions - Standard and
# Enterprise require db.m*/db.r*. The instance class therefore determined the
# edition, not the other way round.
###############################################################################

locals {
  tags = merge(var.tags, { Module = "database" })

  # RDS rejects '/', '"', '@' and spaces in the master password.
  password_override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_db_subnet_group" "this" {
  name        = "${var.name_prefix}-db-subnets"
  description = "Private subnets for the SQL Server instance"
  subnet_ids  = var.private_subnet_ids

  tags = merge(local.tags, { Name = "${var.name_prefix}-db-subnets" })
}

###############################################################################
# Security group
#
# Ingress is granted only to explicitly passed source security groups.
# No CIDR rules, no 0.0.0.0/0. Empty by default - the Lambda SG is attached
# from the root module in stage 5 to avoid a circular module dependency.
###############################################################################

resource "aws_security_group" "db" {
  name        = "${var.name_prefix}-db-sg"
  description = "SQL Server access from the application tier only"
  vpc_id      = var.vpc_id

  tags = merge(local.tags, { Name = "${var.name_prefix}-db-sg" })

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_vpc_security_group_ingress_rule" "db_from_app" {
  for_each = toset(var.allowed_source_security_group_ids)

  security_group_id            = aws_security_group.db.id
  description                  = "TDS from application tier"
  referenced_security_group_id = each.value
  from_port                    = var.db_port
  to_port                      = var.db_port
  ip_protocol                  = "tcp"
}

###############################################################################
# Master credentials
#
# The password is generated by Terraform and written straight to Secrets
# Manager. It is never a variable, never in tfvars, never in the pipeline.
###############################################################################

resource "random_password" "master" {
  length           = 32
  special          = true
  override_special = local.password_override_special
}

resource "aws_secretsmanager_secret" "db" {
  name        = "${var.name_prefix}/rds/master"
  description = "Master credentials for ${var.name_prefix} SQL Server"
  kms_key_id  = var.kms_key_id

  recovery_window_in_days = var.secret_recovery_window_in_days

  tags = merge(local.tags, { Name = "${var.name_prefix}-rds-master" })
}

###############################################################################
# Instance
#
# Note: RDS for SQL Server does NOT accept db_name at creation. Databases are
# created post-provision by the application or a migration step. This is an
# engine limitation, not an omission.
###############################################################################

resource "aws_db_instance" "this" {
  identifier = "${var.name_prefix}-sqlserver"

  engine         = var.engine
  license_model  = "license-included"
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = var.kms_key_id

  username = var.master_username
  password = random_password.master.result
  port     = var.db_port

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false
  multi_az               = var.multi_az

  backup_retention_period    = var.backup_retention_period
  copy_tags_to_snapshot      = true
  auto_minor_version_upgrade = true

  deletion_protection = var.deletion_protection
  skip_final_snapshot = var.skip_final_snapshot

  enabled_cloudwatch_logs_exports = var.enabled_cloudwatch_logs_exports

  tags = merge(local.tags, { Name = "${var.name_prefix}-sqlserver" })

  lifecycle {
    precondition {
      condition     = !(var.multi_az && var.engine == "sqlserver-ex")
      error_message = "SQL Server Express Edition does not support Multi-AZ. Use sqlserver-se or sqlserver-ee with a larger instance class."
    }

    precondition {
      condition     = !(contains(["sqlserver-se", "sqlserver-ee"], var.engine) && startswith(var.instance_class, "db.t"))
      error_message = "Burstable (db.t*) instance classes are only supported on SQL Server Express and Web editions."
    }
  }
}

# Written after the instance exists so the host and port are real values
# rather than (known after apply) placeholders.
resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    engine   = "sqlserver"
    username = var.master_username
    password = random_password.master.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
  })
}
